language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

before_script:
    flake8 .

script:
  - pytest --cov --cov-report=xml .
  - bash <(curl -s https://codecov.io/bash)

